# Generated by Django 5.2.9 on 2025-12-12 11:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 7),
                            ("content_section", 10),
                            ("speaker_grid", 14),
                            ("partner_grid", 18),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Main headline (e.g. 'Real-time event journeys')",
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Highlighted text (e.g. 'orchestrated by data')",
                                    "required": False,
                                },
                            ),
                            2: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. 'odin/hero-bg'. Leave empty for image only.",
                                    "label": "Video Public ID",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. 'odin/hero-bg-poster'. Used for mobile and while video loads.",
                                    "label": "Poster/Image Public ID",
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Get Tickets", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "URL or relative path",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("subtitle", 1),
                                        ("description", 2),
                                        ("video_public_id", 3),
                                        ("poster_public_id", 4),
                                        ("cta_text", 5),
                                        ("cta_link", 6),
                                    ]
                                ],
                                {},
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            9: ("wagtail.blocks.RichTextBlock", (), {}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 8), ("text", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Meet the Legends"},
                            ),
                            12: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("cms_integration.Speaker",),
                                {},
                            ),
                            13: (
                                "wagtail.blocks.ListBlock",
                                (12,),
                                {"label": "Select Speakers to highlight"},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 11),
                                        ("description", 2),
                                        ("featured_speakers", 13),
                                    ]
                                ],
                                {},
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Commercial Partners"},
                            ),
                            16: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("cms_integration.Partner",),
                                {},
                            ),
                            17: (
                                "wagtail.blocks.ListBlock",
                                (16,),
                                {"label": "Select Partners to display"},
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 15), ("partners", 17)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo_public_id", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("headline", "Headline"),
                            ("gold", "Gold"),
                            ("community", "Community"),
                        ],
                        default="community",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        help_text="e.g. VP & Chief AI Scientist", max_length=255
                    ),
                ),
                ("company", models.CharField(help_text="e.g. Meta", max_length=255)),
                (
                    "photo_public_id",
                    models.CharField(
                        help_text="Cloudinary Public ID (e.g. 'wsai/yann-lecun'). Use folder structure!",
                        max_length=255,
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("is_keynote", models.BooleanField(default=False)),
            ],
        ),
    ]
