# Generated by Django 5.2.9 on 2025-12-13 12:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 9),
                    ("content_section", 12),
                    ("speaker_grid", 16),
                    ("partner_grid", 20),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main headline (optional).", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Highlighted text (optional).",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'odin/hero-bg'. If set, takes priority over uploaded video.",
                            "label": "Video Public ID (Cloudinary)",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'odin/hero-bg-poster'. Used as fallback + while video loads.",
                            "label": "Poster/Image Public ID (Cloudinary)",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Upload MP4/WebM. Used only if Video Public ID is empty.",
                            "label": "Upload Video (optional)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Fallback image if no video, or while video loads.",
                            "label": "Upload Poster Image (optional)",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get Tickets", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "URL or relative path", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("video_public_id", 3),
                                ("poster_public_id", 4),
                                ("video_upload", 5),
                                ("poster_upload", 6),
                                ("cta_text", 7),
                                ("cta_link", 8),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    11: ("wagtail.blocks.RichTextBlock", (), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 10), ("text", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Meet the Legends"},
                    ),
                    14: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Speaker",),
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (14,),
                        {"label": "Select Speakers to highlight"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 13),
                                ("description", 2),
                                ("featured_speakers", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Commercial Partners"},
                    ),
                    18: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Partner",),
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {"label": "Select Partners to display"},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 17), ("partners", 19)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_navigation",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "External URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "footer_description",
                    models.TextField(
                        default="Event Intelligence Platform built for speed, clarity, and scale.",
                        max_length=250,
                    ),
                ),
                (
                    "footer_col_1_title",
                    models.CharField(default="Explore", max_length=50),
                ),
                (
                    "footer_col_1_links",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "External URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "footer_col_2_title",
                    models.CharField(default="Company", max_length=50),
                ),
                (
                    "footer_col_2_links",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "External URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
