# Generated by Django 5.2.9 on 2025-12-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0002_alter_homepage_body_navigationsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={
                "verbose_name": "Sponsor / Partner",
                "verbose_name_plural": "Sponsors & Partners",
            },
        ),
        migrations.AlterModelOptions(
            name="speaker",
            options={
                "verbose_name": "Speaker (Person)",
                "verbose_name_plural": "Speakers (People)",
            },
        ),
    ]
