# Generated by Django 5.2.9 on 2025-12-14 13:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0003_alter_partner_options_alter_speaker_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="navigationsettings",
            options={"verbose_name": "Header & Footer Links"},
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 11),
                    ("content_section", 14),
                    ("speaker_grid", 18),
                    ("partner_grid", 22),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main headline (optional).", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Highlighted text (optional).",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (3,),
                        {
                            "help_text": "Optional images shown below the buttons (e.g. sponsor logos, badges).",
                            "label": "Extra hero images (optional)",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'odin/hero-bg'. If set, takes priority over uploaded video.",
                            "label": "Video Public ID (Cloudinary)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'odin/hero-bg-poster'. Used as fallback + while video loads.",
                            "label": "Poster/Image Public ID (Cloudinary)",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Upload MP4/WebM. Used only if Video Public ID is empty.",
                            "label": "Upload Video (optional)",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Fallback image if no video, or while video loads.",
                            "label": "Upload Poster Image (optional)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get Tickets", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "URL or relative path", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("extra_images", 4),
                                ("video_public_id", 5),
                                ("poster_public_id", 6),
                                ("video_upload", 7),
                                ("poster_upload", 8),
                                ("cta_text", 9),
                                ("cta_link", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: ("wagtail.blocks.RichTextBlock", (), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 12), ("text", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Meet the Legends"},
                    ),
                    16: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Speaker",),
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"label": "Select Speakers to highlight"},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("description", 2),
                                ("featured_speakers", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Commercial Partners"},
                    ),
                    20: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Partner",),
                        {},
                    ),
                    21: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {"label": "Select Partners to display"},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("partners", 21)]],
                        {},
                    ),
                },
            ),
        ),
    ]
