# Generated by Django 5.2.9 on 2025-12-14 14:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cms_integration",
            "0004_alter_navigationsettings_options_alter_homepage_body",
        ),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 12),
                    ("content_section", 15),
                    ("speaker_grid", 19),
                    ("partner_grid", 23),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main headline (optional).", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Highlighted text (optional).",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (3,),
                        {
                            "help_text": "Logos / badges displayed over the hero background.",
                            "label": "Extra hero images (optional)",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("center", "Center"),
                                ("bottom", "Bottom"),
                            ],
                            "label": "Extra images position",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'odin/hero-bg'. If set, takes priority over uploaded video.",
                            "label": "Video Public ID (Cloudinary)",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'odin/hero-bg-poster'. Used as fallback + while video loads.",
                            "label": "Poster/Image Public ID (Cloudinary)",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Upload MP4/WebM. Used only if Video Public ID is empty.",
                            "label": "Upload Video (optional)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Fallback image if no video, or while video loads.",
                            "label": "Upload Poster Image (optional)",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get Tickets", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "URL or relative path", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("extra_images", 4),
                                ("extra_images_position", 5),
                                ("video_public_id", 6),
                                ("poster_public_id", 7),
                                ("video_upload", 8),
                                ("poster_upload", 9),
                                ("cta_text", 10),
                                ("cta_link", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    14: ("wagtail.blocks.RichTextBlock", (), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("text", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Meet the Legends"},
                    ),
                    17: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Speaker",),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"label": "Select Speakers to highlight"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 16),
                                ("description", 2),
                                ("featured_speakers", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Commercial Partners"},
                    ),
                    21: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Partner",),
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (21,),
                        {"label": "Select Partners to display"},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 20), ("partners", 22)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="photo_public_id",
            field=models.CharField(
                help_text="Cloudinary Public ID (e.g. 'name,role,company'). Use folder structure!",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "footer_description",
                    models.TextField(
                        default="Event Intelligence Platform built for speed, clarity, and scale.",
                        max_length=250,
                    ),
                ),
                (
                    "footer_col_1_title",
                    models.CharField(default="Explore", max_length=50),
                ),
                (
                    "footer_col_1_links",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "External URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "footer_col_2_title",
                    models.CharField(default="Company", max_length=50),
                ),
                (
                    "footer_col_2_links",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "External URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
            },
        ),
        migrations.CreateModel(
            name="HeaderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Accessibility alt text for the logo (optional).",
                        max_length=120,
                    ),
                ),
                (
                    "primary_navigation",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "External URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "logo_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header",
            },
        ),
        migrations.DeleteModel(
            name="NavigationSettings",
        ),
    ]
