# Generated by Django 5.2.9 on 2025-12-14 15:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cms_integration",
            "0005_alter_homepage_body_alter_speaker_photo_public_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="headersettings",
            name="cta_buttons",
            field=wagtail.fields.StreamField(
                [("cta", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("ghost", "Ghost"),
                            ],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2), ("style", 3)]],
                        {},
                    ),
                },
                help_text="Header CTA buttons shown on desktop + mobile.",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="footer_col_1_links",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="footer_col_2_links",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="headersettings",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [("item", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (3,),
                        {
                            "help_text": "Optional dropdown items under this nav item.",
                            "label": "Submenu links",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2), ("children", 4)]],
                        {},
                    ),
                },
                help_text="Top navigation (supports optional dropdown children).",
            ),
        ),
    ]
