# Generated by Django 5.2.9 on 2025-12-14 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0007_alter_homepage_body"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="event_end_date",
            field=models.DateTimeField(
                blank=True, help_text="Used for Google Event Schema", null=True
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="event_location",
            field=models.CharField(
                blank=True,
                default="Amsterdam",
                help_text="City/Venue for Schema",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="event_start_date",
            field=models.DateTimeField(
                blank=True, help_text="Used for Google Event Schema", null=True
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social Share Image (Facebook/LinkedIn/Twitter). Recommended size: 1200x630.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="structured_data_type",
            field=models.CharField(
                choices=[
                    ("Website", "Website (General)"),
                    ("Event", "Event (Conference/Summit)"),
                    ("Organization", "Organization (Company)"),
                    ("Article", "Article/Blog Post"),
                ],
                default="Website",
                help_text="Tells Google/AI what this page represents.",
                max_length=50,
            ),
        ),
    ]
