# Generated by Django 5.2.9 on 2025-12-14 21:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cms_integration",
            "0008_homepage_event_end_date_homepage_event_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 16),
                    ("content_section", 19),
                    ("speaker_grid", 23),
                    ("partner_grid", 27),
                    ("faq_section", 33),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main headline (optional).", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Highlighted text (optional).",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (3,),
                        {
                            "help_text": "Logos / badges displayed over the hero background.",
                            "label": "Extra hero images (optional)",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("center", "Center"),
                                ("bottom", "Bottom"),
                            ],
                            "label": "Extra images position",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'odin/hero-bg'. If set, takes priority over uploaded video.",
                            "label": "Video Public ID (Cloudinary)",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'odin/hero-bg-poster'. Used as fallback + while video loads.",
                            "label": "Poster/Image Public ID (Cloudinary)",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Upload MP4/WebM. Used only if Video Public ID is empty.",
                            "label": "Upload Video (optional)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Fallback image if no video, or while video loads.",
                            "label": "Upload Poster Image (optional)",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    11: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External URL", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("ghost", "Ghost"),
                            ],
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 10), ("page", 11), ("url", 12), ("style", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (14,),
                        {
                            "help_text": "Add one or more buttons under the hero text.",
                            "label": "Hero CTA buttons",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("extra_images", 4),
                                ("extra_images_position", 5),
                                ("video_public_id", 6),
                                ("poster_public_id", 7),
                                ("video_upload", 8),
                                ("poster_upload", 9),
                                ("cta_buttons", 15),
                            ]
                        ],
                        {},
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    18: ("wagtail.blocks.RichTextBlock", (), {}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 17), ("text", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Meet the Legends"},
                    ),
                    21: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Speaker",),
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (21,),
                        {"label": "Select Speakers to highlight"},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 20),
                                ("description", 2),
                                ("featured_speakers", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Commercial Partners"},
                    ),
                    25: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Partner",),
                        {},
                    ),
                    26: (
                        "wagtail.blocks.ListBlock",
                        (25,),
                        {"label": "Select Partners to display"},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 24), ("partners", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently Asked Questions"},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Question", "required": True},
                    ),
                    30: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Answer", "required": True},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 29), ("answer", 30)]],
                        {},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {"label": "Questions"}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 28), ("faqs", 32)]],
                        {},
                    ),
                },
            ),
        ),
    ]
