# Generated by Django 5.2.9 on 2025-12-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0009_alter_homepage_body"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="partner",
            constraint=models.UniqueConstraint(
                fields=("name",), name="uniq_partner_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="speaker",
            constraint=models.UniqueConstraint(
                fields=("name", "company"), name="uniq_speaker_name_company"
            ),
        ),
    ]
