# Generated by Django 5.2.9 on 2025-12-27 21:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0010_partner_uniq_partner_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="partner",
            name="uniq_partner_name",
        ),
        migrations.RemoveConstraint(
            model_name="speaker",
            name="uniq_speaker_name_company",
        ),
        migrations.AddConstraint(
            model_name="partner",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="uniq_partner_name_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="speaker",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                django.db.models.functions.text.Lower("company"),
                name="uniq_speaker_name_company_ci",
            ),
        ),
    ]
