# Generated by Django 5.2.9 on 2025-12-29 17:19

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0011_remove_partner_uniq_partner_name_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakersIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="SponsorsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated from name (editable). Used in URLs.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="speaker",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated from name (editable). Used in URLs.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="headersettings",
            name="cta_buttons",
            field=wagtail.fields.StreamField(
                [("cta", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("ghost", "Ghost"),
                            ],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2), ("style", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="headersettings",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [("item", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (3,),
                        {
                            "help_text": "Optional dropdown items under this nav item.",
                            "label": "Submenu links",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2), ("children", 4)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Recommended size: 1200x630.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="photo_public_id",
            field=models.CharField(max_length=255),
        ),
    ]
