# Generated by Django 5.2.9 on 2026-01-13 18:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cms_integration",
            "0012_speakersindexpage_sponsorsindexpage_partner_slug_and_more",
        ),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footersettings",
            options={"verbose_name": "Footer Configuration"},
        ),
        migrations.AlterModelOptions(
            name="headersettings",
            options={"verbose_name": "Header Configuration"},
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={
                "ordering": ["name"],
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
            },
        ),
        migrations.AlterModelOptions(
            name="speaker",
            options={
                "ordering": ["name"],
                "verbose_name": "Speaker",
                "verbose_name_plural": "Speakers",
            },
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="footer_description",
            field=models.TextField(
                default="Event Intelligence Platform built for speed, clarity, and scale.",
                help_text="Small blurb appearing below the logo in the footer.",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="headersettings",
            name="cta_buttons",
            field=wagtail.fields.StreamField(
                [("cta", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary (Green)"),
                                ("secondary", "Secondary (Border)"),
                                ("ghost", "Ghost (Text)"),
                            ],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2), ("style", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="headersettings",
            name="logo_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Text description of the logo for screen readers (e.g. 'DXP Odin').",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="headersettings",
            name="logo_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Upload the site logo (SVG or Transparent PNG preferred).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="headersettings",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [("item", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (3,),
                        {
                            "help_text": "Add links here to create a dropdown menu.",
                            "label": "Dropdown Items",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2), ("children", 4)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 15),
                    ("content_section", 18),
                    ("speaker_grid", 23),
                    ("partner_grid", 27),
                    ("faq_section", 33),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "The Future of AI",
                            "help_text": "Main headline (H1). Keep it punchy.",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Gradient text below the headline (optional).",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Small uppercase text above the headline (e.g., 'OCTOBER 2026 • AMSTERDAM').",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The 'Public ID' from Cloudinary (e.g., 'odin/hero-bg'). Optimized for streaming.",
                            "label": "Cloudinary Video ID",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image ID to show while video loads (e.g., 'odin/hero-poster').",
                            "label": "Cloudinary Poster ID",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Upload MP4 if not using Cloudinary ID.",
                            "label": "Upload Video (Fallback)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image if not using Cloudinary ID.",
                            "label": "Upload Poster (Fallback)",
                            "required": False,
                        },
                    ),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    8: (
                        "wagtail.blocks.ListBlock",
                        (7,),
                        {
                            "help_text": "Add sponsor logos or badges to float above the title.",
                            "label": "Floating Logos",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to appear on the button (e.g., 'Get Tickets').",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to an internal page.", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to an external site (e.g., https://google.com).",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary (Green Glow)"),
                                ("secondary", "Secondary (Glass/Border)"),
                                ("ghost", "Ghost (Text Link)"),
                            ],
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 9), ("page", 10), ("url", 11), ("style", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {"label": "Call to Action Buttons", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("video_public_id", 3),
                                ("poster_public_id", 4),
                                ("video_upload", 5),
                                ("poster_upload", 6),
                                ("extra_images", 8),
                                ("cta_buttons", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section title.", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "ol"],
                            "help_text": "Main content. Formatting is limited to keep the design clean.",
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 16), ("text", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Meet the Legends"},
                    ),
                    20: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Introductory text below the title.",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Speaker",),
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (21,),
                        {
                            "help_text": "Search and select speakers to display in this grid.",
                            "label": "Select Speakers",
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 19),
                                ("description", 20),
                                ("featured_speakers", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Commercial Partners"},
                    ),
                    25: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Partner",),
                        {},
                    ),
                    26: (
                        "wagtail.blocks.ListBlock",
                        (25,),
                        {
                            "help_text": "Search and select sponsors to display.",
                            "label": "Select Partners",
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 24), ("partners", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently Asked Questions"},
                    ),
                    29: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    30: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 29), ("answer", 30)]],
                        {},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {"label": "Questions"}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 28), ("faqs", 32)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="event_end_date",
            field=models.DateTimeField(
                blank=True, help_text="For Google Event Schema", null=True
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="event_start_date",
            field=models.DateTimeField(
                blank=True, help_text="For Google Event Schema", null=True
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo_public_id",
            field=models.CharField(
                help_text="Cloudinary Public ID for the logo. White/Transparent PNG works best.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated from name.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="company",
            field=models.CharField(help_text="e.g. 'OpenAI'", max_length=255),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="is_keynote",
            field=models.BooleanField(
                default=False,
                help_text="Check this to prioritize this speaker in lists.",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="linkedin_url",
            field=models.URLField(
                blank=True, help_text="Optional LinkedIn profile link."
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="photo_public_id",
            field=models.CharField(
                help_text="Cloudinary Public ID for their headshot (e.g. 'speakers/elon-musk'). Focus on the face.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="role",
            field=models.CharField(
                help_text="e.g. 'VP of Engineering'", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated from name. Used in URLs.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
