# Generated by Django 5.2.9 on 2026-01-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0013_alter_footersettings_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="show_floating_social_bar",
            field=models.BooleanField(
                default=True,
                help_text="If checked, a glass sidebar with social icons will appear on the right side of the screen (Desktop only).",
                verbose_name="Enable Floating Social Bar",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="social_facebook",
            field=models.URLField(blank=True, help_text="Facebook URL"),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="social_instagram",
            field=models.URLField(blank=True, help_text="Instagram URL"),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="social_linkedin",
            field=models.URLField(blank=True, help_text="LinkedIn URL"),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="social_x",
            field=models.URLField(blank=True, help_text="X (Twitter) URL"),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="social_youtube",
            field=models.URLField(blank=True, help_text="YouTube URL"),
        ),
    ]
