# Generated by Django 5.2.9 on 2026-01-14 10:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0014_footersettings_show_floating_social_bar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 15),
                    ("countdown", 22),
                    ("content_section", 25),
                    ("testimonial_grid", 33),
                    ("speaker_grid", 38),
                    ("partner_grid", 42),
                    ("faq_section", 48),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "The Future of AI",
                            "help_text": "Main headline (H1). Keep it punchy.",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Gradient text below the headline (optional).",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Small uppercase text above the headline (e.g., 'OCTOBER 2026 • AMSTERDAM').",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The 'Public ID' from Cloudinary (e.g., 'odin/hero-bg'). Optimized for streaming.",
                            "label": "Cloudinary Video ID",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image ID to show while video loads (e.g., 'odin/hero-poster').",
                            "label": "Cloudinary Poster ID",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Upload MP4 if not using Cloudinary ID.",
                            "label": "Upload Video (Fallback)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image if not using Cloudinary ID.",
                            "label": "Upload Poster (Fallback)",
                            "required": False,
                        },
                    ),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    8: (
                        "wagtail.blocks.ListBlock",
                        (7,),
                        {
                            "help_text": "Add sponsor logos or badges to float above the title.",
                            "label": "Floating Logos",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to appear on the button (e.g., 'Get Tickets').",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to an internal page.", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to an external site (e.g., https://google.com).",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary (Green Glow)"),
                                ("secondary", "Secondary (Glass/Border)"),
                                ("ghost", "Ghost (Text Link)"),
                            ],
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 9), ("page", 10), ("url", 11), ("style", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {"label": "Call to Action Buttons", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("video_public_id", 3),
                                ("poster_public_id", 4),
                                ("video_upload", 5),
                                ("poster_upload", 6),
                                ("extra_images", 8),
                                ("cta_buttons", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Turn this ON/OFF without removing the block.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Ticket Flash Sale Ends In"},
                    ),
                    18: (
                        "wagtail.blocks.DateTimeBlock",
                        (),
                        {"help_text": "The date/time the countdown ends."},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Sale Ended",
                            "help_text": "Text to show when time is up.",
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button Label", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Button URL", "required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("enabled", 16),
                                ("title", 17),
                                ("target_date", 18),
                                ("end_message", 19),
                                ("cta_label", 20),
                                ("cta_url", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section title.", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "ol"],
                            "help_text": "Main content. Formatting is limited to keep the design clean.",
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 23), ("text", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What People Are Saying", "required": False},
                    ),
                    27: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    28: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "e.g. Microsoft", "required": False},
                    ),
                    30: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 27),
                                ("author", 28),
                                ("role", 28),
                                ("organization", 29),
                                ("logo", 30),
                            ]
                        ],
                        {},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {"label": "Testimonials"}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 26), ("quotes", 32)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Meet the Legends"},
                    ),
                    35: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Introductory text below the title.",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Speaker",),
                        {},
                    ),
                    37: (
                        "wagtail.blocks.ListBlock",
                        (36,),
                        {
                            "help_text": "Search and select speakers to display in this grid.",
                            "label": "Select Speakers",
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 34),
                                ("description", 35),
                                ("featured_speakers", 37),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Commercial Partners"},
                    ),
                    40: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Partner",),
                        {},
                    ),
                    41: (
                        "wagtail.blocks.ListBlock",
                        (40,),
                        {
                            "help_text": "Search and select sponsors to display.",
                            "label": "Select Partners",
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 39), ("partners", 41)]],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently Asked Questions"},
                    ),
                    44: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    45: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 44), ("answer", 45)]],
                        {},
                    ),
                    47: ("wagtail.blocks.ListBlock", (46,), {"label": "Questions"}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 43), ("faqs", 47)]],
                        {},
                    ),
                },
            ),
        ),
    ]
