# Generated by Django 5.2.9 on 2026-01-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0015_alter_homepage_body"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashSaleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Check this to show the countdown timer on the site.",
                        verbose_name="Activate Flash Sale",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="2-For-1 Ticket Flash Sale Ends In",
                        help_text="The headline above the timer.",
                        max_length=100,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="When does the sale end?", null=True
                    ),
                ),
                (
                    "end_message",
                    models.CharField(
                        default="Flash Sale has ended!",
                        help_text="What to show when the timer hits zero.",
                        max_length=100,
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        blank=True,
                        default="Get Tickets",
                        help_text="Button label text.",
                        max_length=50,
                    ),
                ),
                (
                    "cta_url",
                    models.URLField(
                        blank=True,
                        help_text="Where the button should link to.",
                        verbose_name="Button URL",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flash Sale Configuration",
            },
        ),
    ]
