# Generated by Django 5.2.9 on 2026-01-14 18:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0016_flashsalesettings"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 18),
                    ("countdown", 25),
                    ("content_section", 28),
                    ("testimonial_grid", 36),
                    ("speaker_grid", 41),
                    ("partner_grid", 45),
                    ("faq_section", 51),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "The Future of AI",
                            "help_text": "Main headline (H1). Keep it punchy.",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Gradient text below the headline (optional).",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Small uppercase text above the headline (e.g., 'OCTOBER 2026 • AMSTERDAM').",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "First paragraph directly under the H1. If empty, 'Subtitle' will be used.",
                            "label": "Lead paragraph (below H1)",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 220, "required": True},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {
                            "help_text": "Add more lines under the lead (smaller text).",
                            "label": "Extra paragraphs (below lead)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The 'Public ID' from Cloudinary (e.g., 'odin/hero-bg'). Optimized for streaming.",
                            "label": "Cloudinary Video ID",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image ID to show while video loads (e.g., 'odin/hero-poster').",
                            "label": "Cloudinary Poster ID",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Upload MP4 if not using Cloudinary ID.",
                            "label": "Upload Video (Fallback)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image if not using Cloudinary ID.",
                            "label": "Upload Poster (Fallback)",
                            "required": False,
                        },
                    ),
                    10: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "help_text": "Add sponsor logos or badges to float above the title.",
                            "label": "Floating Logos",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to appear on the button (e.g., 'Get Tickets').",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to an internal page.", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to an external site (e.g., https://google.com).",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary (Green Glow)"),
                                ("secondary", "Secondary (Glass/Border)"),
                                ("ghost", "Ghost (Text Link)"),
                            ],
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 12), ("page", 13), ("url", 14), ("style", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"label": "Call to Action Buttons", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("lead", 3),
                                ("paragraphs", 5),
                                ("video_public_id", 6),
                                ("poster_public_id", 7),
                                ("video_upload", 8),
                                ("poster_upload", 9),
                                ("extra_images", 11),
                                ("cta_buttons", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Turn this ON/OFF without removing the block.",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Ticket Flash Sale Ends In"},
                    ),
                    21: (
                        "wagtail.blocks.DateTimeBlock",
                        (),
                        {"help_text": "The date/time the countdown ends."},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Sale Ended",
                            "help_text": "Text to show when time is up.",
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button Label", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Button URL", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("enabled", 19),
                                ("title", 20),
                                ("target_date", 21),
                                ("end_message", 22),
                                ("cta_label", 23),
                                ("cta_url", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section title.", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "ol"],
                            "help_text": "Main content. Formatting is limited to keep the design clean.",
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 26), ("text", 27)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What People Are Saying", "required": False},
                    ),
                    30: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    31: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "e.g. Microsoft", "required": False},
                    ),
                    33: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 30),
                                ("author", 31),
                                ("role", 31),
                                ("organization", 32),
                                ("logo", 33),
                            ]
                        ],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {"label": "Testimonials"}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 29), ("quotes", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Meet the Legends"},
                    ),
                    38: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Introductory text below the title.",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Speaker",),
                        {},
                    ),
                    40: (
                        "wagtail.blocks.ListBlock",
                        (39,),
                        {
                            "help_text": "Search and select speakers to display in this grid.",
                            "label": "Select Speakers",
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 37),
                                ("description", 38),
                                ("featured_speakers", 40),
                            ]
                        ],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Commercial Partners"},
                    ),
                    43: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Partner",),
                        {},
                    ),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (43,),
                        {
                            "help_text": "Search and select sponsors to display.",
                            "label": "Select Partners",
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 42), ("partners", 44)]],
                        {},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently Asked Questions"},
                    ),
                    47: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    48: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 47), ("answer", 48)]],
                        {},
                    ),
                    50: ("wagtail.blocks.ListBlock", (49,), {"label": "Questions"}),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 46), ("faqs", 50)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.CreateModel(
            name="CookieSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Show the consent banner to new visitors.",
                        verbose_name="Enable Cookie Banner",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="We value your privacy", max_length=100),
                ),
                (
                    "message",
                    models.TextField(
                        default="We use cookies to enhance your browsing experience, serve personalized ads or content, and analyze our traffic."
                    ),
                ),
                (
                    "accept_button_text",
                    models.CharField(default="Accept All", max_length=50),
                ),
                (
                    "decline_button_text",
                    models.CharField(default="Decline", max_length=50),
                ),
                (
                    "privacy_policy_url",
                    models.URLField(
                        blank=True, help_text="External link if page not selected"
                    ),
                ),
                (
                    "privacy_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cookie Consent Settings",
            },
        ),
    ]
