# Generated by Django 5.2.9 on 2026-01-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0018_partner_logo_upload_speaker_photo_upload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="photo_public_id",
            field=models.CharField(
                blank=True,
                help_text="Cloudinary Public ID fallback (e.g. 'speakers/elon-musk').",
                max_length=255,
            ),
        ),
    ]
