# Generated by Django 5.2.9 on 2026-01-21 11:13

import django.db.models.deletion
import django.db.models.functions.text
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0019_alter_speaker_photo_public_id"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnersIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={
                "ordering": ["type", "name"],
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.RemoveField(
            model_name="partner",
            name="tier",
        ),
        migrations.AddField(
            model_name="partner",
            name="type",
            field=models.CharField(
                choices=[
                    ("community", "Community Partner"),
                    ("media", "Media Partner"),
                    ("technology", "Technology Partner"),
                    ("institutional", "Institutional Partner"),
                ],
                default="community",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 18),
                    ("countdown", 25),
                    ("content_section", 27),
                    ("testimonial_grid", 33),
                    ("speaker_grid", 38),
                    ("sponsor_section", 42),
                    ("partner_carousel", 46),
                    ("faq_section", 52),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "The Future of AI",
                            "label": "Main Headline (H1)",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Fallback lead text shown above the H1 if 'Lead paragraph' is empty.",
                            "label": "Lead (Legacy / Optional)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The first paragraph under the headline (gradient style).",
                            "label": "Main paragraph (Below H1)",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Short kicker shown above the headline (preferred).",
                            "label": "Lead paragraph (Above H1)",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 220, "required": True},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {
                            "label": "Extra paragraphs (Below main paragraph)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Cloudinary Video ID", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Cloudinary Poster ID", "required": False},
                    ),
                    8: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Upload Video (Fallback)", "required": False},
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Upload Poster (Fallback)", "required": False},
                    ),
                    10: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "help_text": "If set, this replaces the lead text at the very top.",
                            "label": "Brain / Logo Image",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to appear on the button (e.g., 'Get Tickets').",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to an internal page.", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to an external site (e.g., https://google.com).",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary (Green Glow)"),
                                ("secondary", "Secondary (Glass/Border)"),
                                ("ghost", "Ghost (Text Link)"),
                            ],
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 12), ("page", 13), ("url", 14), ("style", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"label": "Call to Action Buttons", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("lead", 3),
                                ("paragraphs", 5),
                                ("video_public_id", 6),
                                ("poster_public_id", 7),
                                ("video_upload", 8),
                                ("poster_upload", 9),
                                ("extra_images", 11),
                                ("cta_buttons", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Turn this ON/OFF without removing the block.",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Ticket Flash Sale Ends In"},
                    ),
                    21: ("wagtail.blocks.DateTimeBlock", (), {}),
                    22: ("wagtail.blocks.CharBlock", (), {"default": "Sale Ended"}),
                    23: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    24: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("enabled", 19),
                                ("title", 20),
                                ("target_date", 21),
                                ("end_message", 22),
                                ("cta_label", 23),
                                ("cta_url", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ul", "ol"]},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 23), ("text", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What People Are Saying", "required": False},
                    ),
                    29: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    30: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 29),
                                ("author", 23),
                                ("role", 23),
                                ("organization", 23),
                                ("logo", 30),
                            ]
                        ],
                        {},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {"label": "Testimonials"}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 28), ("quotes", 32)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Meet the Legends"},
                    ),
                    35: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    36: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Speaker",),
                        {},
                    ),
                    37: (
                        "wagtail.blocks.ListBlock",
                        (36,),
                        {"label": "Select Speakers"},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 34),
                                ("description", 35),
                                ("featured_speakers", 37),
                            ]
                        ],
                        {},
                    ),
                    39: ("wagtail.blocks.CharBlock", (), {"default": "Our Sponsors"}),
                    40: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Sponsor",),
                        {},
                    ),
                    41: (
                        "wagtail.blocks.ListBlock",
                        (40,),
                        {
                            "help_text": "Commercial sponsors. Displayed by tier.",
                            "label": "Select Sponsors",
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 39), ("sponsors", 41)]],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Community Partners"},
                    ),
                    44: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Partner",),
                        {},
                    ),
                    45: (
                        "wagtail.blocks.ListBlock",
                        (44,),
                        {
                            "help_text": "Community, media, technology, or institutional partners.",
                            "label": "Select Partners",
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 43), ("partners", 45)]],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently Asked Questions"},
                    ),
                    48: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    49: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 48), ("answer", 49)]],
                        {},
                    ),
                    51: ("wagtail.blocks.ListBlock", (50,), {"label": "Questions"}),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 47), ("faqs", 51)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="event_location",
            field=models.CharField(
                blank=True,
                default="Amsterdam",
                help_text="City / Venue for Schema",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo_public_id",
            field=models.CharField(
                blank=True,
                help_text="Cloudinary Public ID for the logo.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="is_keynote",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from name.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "logo_public_id",
                    models.CharField(
                        blank=True,
                        help_text="Cloudinary Public ID for the logo.",
                        max_length=255,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("platinum", "Platinum"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                        ],
                        default="bronze",
                        max_length=50,
                    ),
                ),
                (
                    "logo_upload",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload/select a logo from Wagtail Images (recommended).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["tier", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uniq_sponsor_name_ci",
                    )
                ],
            },
        ),
    ]
