# Generated by Django 5.2.9 on 2026-01-21 13:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0020_partnersindexpage_alter_partner_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 18),
                    ("countdown", 25),
                    ("content_section", 27),
                    ("testimonial_grid", 33),
                    ("nexus_grid", 44),
                    ("speaker_grid", 49),
                    ("sponsor_section", 53),
                    ("partner_carousel", 57),
                    ("faq_section", 63),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "The Future of AI",
                            "label": "Main Headline (H1)",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Fallback lead text shown above the H1 if 'Lead paragraph' is empty.",
                            "label": "Lead (Legacy / Optional)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The first paragraph under the headline (gradient style).",
                            "label": "Main paragraph (Below H1)",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Short kicker shown above the headline (preferred).",
                            "label": "Lead paragraph (Above H1)",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 220, "required": True},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {
                            "label": "Extra paragraphs (Below main paragraph)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Cloudinary Video ID", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Cloudinary Poster ID", "required": False},
                    ),
                    8: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Upload Video (Fallback)", "required": False},
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Upload Poster (Fallback)", "required": False},
                    ),
                    10: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "help_text": "If set, this replaces the lead text at the very top.",
                            "label": "Brain / Logo Image",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to appear on the button (e.g., 'Get Tickets').",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to an internal page.", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to an external site (e.g., https://google.com).",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary (Green Glow)"),
                                ("secondary", "Secondary (Glass/Border)"),
                                ("ghost", "Ghost (Text Link)"),
                            ],
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 12), ("page", 13), ("url", 14), ("style", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"label": "Call to Action Buttons", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("lead", 3),
                                ("paragraphs", 5),
                                ("video_public_id", 6),
                                ("poster_public_id", 7),
                                ("video_upload", 8),
                                ("poster_upload", 9),
                                ("extra_images", 11),
                                ("cta_buttons", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Turn this ON/OFF without removing the block.",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Ticket Flash Sale Ends In"},
                    ),
                    21: ("wagtail.blocks.DateTimeBlock", (), {}),
                    22: ("wagtail.blocks.CharBlock", (), {"default": "Sale Ended"}),
                    23: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    24: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("enabled", 19),
                                ("title", 20),
                                ("target_date", 21),
                                ("end_message", 22),
                                ("cta_label", 23),
                                ("cta_url", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ul", "ol"]},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 23), ("text", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What People Are Saying", "required": False},
                    ),
                    29: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    30: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 29),
                                ("author", 23),
                                ("role", 23),
                                ("organization", 23),
                                ("logo", 30),
                            ]
                        ],
                        {},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {"label": "Testimonials"}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 28), ("quotes", 32)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional Section Heading", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Small eyebrow text (e.g., 'Track 6')",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main title (e.g., 'AI MEDIA')",
                            "required": True,
                        },
                    ),
                    37: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "ol"],
                            "help_text": "The descriptive content.",
                        },
                    ),
                    38: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Wagtail Image (fallback)", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Cloudinary Public ID (e.g., 'v1234/my-image')",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button Label", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Button URL", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tagline", 35),
                                ("headline", 36),
                                ("description", 37),
                                ("image_upload", 38),
                                ("image_public_id", 39),
                                ("cta_label", 40),
                                ("cta_url", 41),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {"label": "Feature Rows"}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 34), ("features", 43)]],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Meet the Legends"},
                    ),
                    46: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    47: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Speaker",),
                        {},
                    ),
                    48: (
                        "wagtail.blocks.ListBlock",
                        (47,),
                        {"label": "Select Speakers"},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 45),
                                ("description", 46),
                                ("featured_speakers", 48),
                            ]
                        ],
                        {},
                    ),
                    50: ("wagtail.blocks.CharBlock", (), {"default": "Our Sponsors"}),
                    51: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Sponsor",),
                        {},
                    ),
                    52: (
                        "wagtail.blocks.ListBlock",
                        (51,),
                        {
                            "help_text": "Commercial sponsors. Displayed by tier.",
                            "label": "Select Sponsors",
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 50), ("sponsors", 52)]],
                        {},
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Community Partners"},
                    ),
                    55: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("cms_integration.Partner",),
                        {},
                    ),
                    56: (
                        "wagtail.blocks.ListBlock",
                        (55,),
                        {
                            "help_text": "Community, media, technology, or institutional partners.",
                            "label": "Select Partners",
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 54), ("partners", 56)]],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently Asked Questions"},
                    ),
                    59: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    60: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 59), ("answer", 60)]],
                        {},
                    ),
                    62: ("wagtail.blocks.ListBlock", (61,), {"label": "Questions"}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 58), ("faqs", 62)]],
                        {},
                    ),
                },
            ),
        ),
    ]
