# Generated by Django 5.2.9 on 2026-01-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0021_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="company_address",
            field=models.TextField(
                default="14 Princeton Mews\n167 London Road\nKingston upon Thames\nKT2 6PT",
                help_text="Full physical address (use line breaks).",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="company_name",
            field=models.CharField(
                default="Inspired Minds Media Ltd / World Summit AI Ltd",
                help_text="Official company name for the footer bottom.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="company_numbers",
            field=models.TextField(
                default="Company number: 10577140\nVAT number: NL82552426B01",
                help_text="Registration and VAT numbers.",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="copyright_text",
            field=models.CharField(
                default="© Copyright 2026 • All rights reserved", max_length=255
            ),
        ),
    ]
