# Generated by Django 5.2.9 on 2026-01-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0022_footersettings_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footersettings",
            name="company_address",
            field=models.TextField(
                default="Level 5, The Innovation Hub\n123 Future Tech Boulevard\nLondon, EC1V 9XX\nUnited Kingdom",
                help_text="Full physical address. Use line breaks for formatting.",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="company_name",
            field=models.CharField(
                default="Nexus AI Events Global Ltd",
                help_text="The official registered company name.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="company_numbers",
            field=models.TextField(
                default="Company No: 12345678\nVAT No: GB 987 6543 21",
                help_text="Registration and VAT numbers (separate with line breaks).",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="footer_description",
            field=models.TextField(
                default="The premier global platform for artificial intelligence and future technology events. Connecting minds, shaping the future.",
                help_text="A short, high-impact value proposition appearing below the logo.",
                max_length=250,
            ),
        ),
    ]
