# Generated by Django 5.2.9 on 2026-01-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_integration", "0023_alter_footersettings_company_address_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footersettings",
            name="show_floating_social_bar",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="social_facebook",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="social_instagram",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="social_linkedin",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="social_x",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="social_youtube",
        ),
        migrations.AddField(
            model_name="footersettings",
            name="show_footer_social_icons",
            field=models.BooleanField(
                default=True,
                help_text="Controls ONLY the icon row inside the footer (templates/partials/footer.html).",
                verbose_name="Show Social Icons Inside Footer",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="footer_description",
            field=models.TextField(
                default="Global AI & future-tech events platform. Connecting minds, shaping the future.",
                help_text="A short, high-impact value proposition appearing below the logo.",
                max_length=250,
            ),
        ),
        migrations.CreateModel(
            name="SocialLinksSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn URL")),
                ("x", models.URLField(blank=True, verbose_name="X (Twitter) URL")),
                (
                    "instagram",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                ("youtube", models.URLField(blank=True, verbose_name="YouTube URL")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook URL")),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Links (URLs)",
            },
        ),
        migrations.CreateModel(
            name="SocialSidebarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Shows the floating sidebar on the right. Template: templates/partials/social_floating.html",
                        verbose_name="Enable Floating Social Sidebar",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Sidebar (Toggle)",
            },
        ),
    ]
