# Generated by Django 5.2.9 on 2026-01-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cms_integration",
            "0024_remove_footersettings_show_floating_social_bar_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="enquiries_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact email shown in the footer.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="enquiries_phone",
            field=models.CharField(
                blank=True,
                help_text="Optional phone number (e.g. +44 20 1234 5678).",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="enquiries_title",
            field=models.CharField(
                default="Enquiries",
                help_text="Heading shown above the contact details.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="show_enquiries_block",
            field=models.BooleanField(
                default=True,
                help_text="Toggle the contact section in the footer.",
                verbose_name="Show Contact Block",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="company_address",
            field=models.TextField(
                default="Level 5, The Innovation Hub\n123 Future Tech Boulevard\nLondon, EC1V 9XX\nUnited Kingdom"
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="company_name",
            field=models.CharField(
                default="Nexus AI Events Global Ltd", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="company_numbers",
            field=models.TextField(
                default="Company No: 12345678\nVAT No: GB 987 6543 21"
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="copyright_text",
            field=models.CharField(
                default="All rights reserved",
                help_text="Text shown after the automatic year.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="show_footer_social_icons",
            field=models.BooleanField(
                default=True, verbose_name="Show Social Icons Inside Footer"
            ),
        ),
    ]
